# NUMPY

# ARRAY
shape funtion

In [1]:
import numpy as np

In [16]:
arr_1 = [1, 2, 3, 4, 5]
arr_1 = arr_1 * 2
print(arr_1)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [18]:
arr_1 = [1, 2, 3, 4, 5]
arr_2 = np.array(arr_1)
print(type(arr_2))
print(arr_2)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [12]:
arr_3 = arr_2 + 1
print(arr_3)

[2 3 4 5 6]


In [13]:
arr_3 += 1
print(arr_3)

[3 4 5 6 7]


In [14]:
arr_4 = arr_3 + arr_2
print(arr_4)

[ 4  6  8 10 12]


In [19]:
arr_5 = arr_2 * arr_1
print(arr_5)

[ 1  4  9 16 25]


In [20]:
arr_5[0]

1

In [21]:
arr_5[1:]

array([ 4,  9, 16, 25])

In [22]:
arr_5.shape

(5,)

In [23]:
len(arr_5)

5

In [24]:
arr_6 = np.array([[1, 2, 3],["a", "b", "c"]])
arr_6.shape

(2, 3)

In [41]:
l1 = [1, 2, 3, "4", 5.0]
arr1= np.array(l1)
arr1

array(['1', '2', '3', '4', '5.0'], dtype='<U11')

In [42]:
type(arr1)

numpy.ndarray

In [43]:
arr1.dtype

dtype('<U11')

In [46]:
arr1.size

5

In [47]:
arr1.shape

(5,)

In [48]:
np.shape(arr_1)

(5,)

In [50]:
arr1.ndim

1

In [51]:
arr1

array(['1', '2', '3', '4', '5.0'], dtype='<U11')

In [52]:
arr1.fill(3)

In [53]:
arr1

array(['3', '3', '3', '3', '3'], dtype='<U11')

#MATRIX

In [56]:
m1 = np.array([[1,2, 3],[4, 5, 6],[7, 8, 9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
m1.shape

(3, 3)

In [58]:
#total number of items
m1.size

9

In [59]:
m1.ndim

2

In [60]:
m1[1,2]

6

In [63]:
m1[1,2] = 16
m1

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8,  9]])

In [64]:
m1[2]

array([7, 8, 9])

In [67]:
m1[:,2]

array([ 3, 16,  9])

In [68]:
m1[1,0:2]

array([4, 5])

In [69]:
m1 = np.array([[1,2, 3],[4, 5, 6],[7, 8, 9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
m2 = m1
m2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
m2[1,2] = 600
m2

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [73]:
m1

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [75]:
m3 = m1.copy()
m3

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [76]:
m3[1,2] = 700
m3

array([[  1,   2,   3],
       [  4,   5, 700],
       [  7,   8,   9]])

In [77]:
m1

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [79]:
m4 = np.arange(0,100,20)
m4

array([ 0, 20, 40, 60, 80])

In [80]:
# Tạo ra 10 số random từ 0 đến 1
m5 = np.random.rand(10)
m5

array([0.66506058, 0.96845157, 0.29213852, 0.83277925, 0.50966532,
       0.54867785, 0.64522268, 0.62336355, 0.682779  , 0.9256173 ])

# DataType and Convention to Numpy

In [81]:
arr1 = np.array([1, 2, 3, 4], dtype = np.float32)
arr1

array([1., 2., 3., 4.], dtype=float32)

In [83]:
arr1.nbytes

16

In [84]:
arr2 =  np.array([1, 2.0, "3"], dtype = np.object)
arr2

array([1, 2.0, '3'], dtype=object)

In [86]:
arr2 * 3

array([3, 6.0, '333'], dtype=object)

In [88]:
arr3 = np.array([1, 2, 3])
np.asarray(arr3,dtype = np.float32)
arr3

array([1, 2, 3])

In [90]:
arr4 = np.asarray(arr3, dtype = np.float32)
arr4

array([1., 2., 3.], dtype=float32)

# Mathematical functions in Numpy

In [92]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
np.sum(a1)

21

In [94]:
a1.sum()

21

In [95]:
np.sum(a1, axis = 1)

array([ 6, 15])

In [96]:
np.sum(a1,axis = 0)

array([5, 7, 9])

In [97]:
#nhân các phẩn tử của mảng
a1.prod()

720

In [98]:
a1.prod(axis = 0)

array([ 4, 10, 18])

In [99]:
a1.prod(axis = 1)

array([  6, 120])

In [100]:
a1.min()

1

In [101]:
a1.min(axis = 0)

array([1, 2, 3])

In [102]:
a1.min(axis = 1)

array([1, 4])

In [103]:
a1.max()

6

In [104]:
a1.max(axis = 1)

array([3, 6])

In [105]:
a1.max(axis = 0)

array([4, 5, 6])

In [106]:
#Lấy index của phần tử min
a1.argmin()

0

In [107]:
a1.argmin(axis = 0)

array([0, 0, 0], dtype=int64)

In [108]:
a1.argmin(axis = 1)

array([0, 0], dtype=int64)

In [109]:
a1.argmax()

5

In [110]:
# Lấy trung vị
a1.mean()

3.5

In [111]:
a1.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [112]:
a1.mean(axis = 1)

array([2., 5.])

In [113]:
a1.std()

1.707825127659933

In [114]:
# độ lệch chuẩn 
a1.std(axis = 1)

array([0.81649658, 0.81649658])

In [115]:
# bình phương độ lệch chuẩn
a1.var()

2.9166666666666665

In [116]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
# kẹp dữ liệu: Những dl <2 --> gán thành 2
# những dl >4 --> gán thành 4
# numpy.clip(a, a_min, a_max, out=None)
a1.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [118]:
#làm tròn
a2 = np.array([4.12, 5.5, 6.666])
a2.round()

array([4., 6., 7.])

In [119]:
a2.round(decimals = 2)

array([4.12, 5.5 , 6.67])

# Order functions in Numpy

In [2]:
import numpy as np

In [3]:
a1 = np.array([[5.5, 1.1, 8.7],[4.5, 9.8, 0.9]])
a1

array([[5.5, 1.1, 8.7],
       [4.5, 9.8, 0.9]])

In [4]:
np.sort(a1)

array([[1.1, 5.5, 8.7],
       [0.9, 4.5, 9.8]])

In [5]:
a1

array([[5.5, 1.1, 8.7],
       [4.5, 9.8, 0.9]])

In [6]:
np.argsort(a1)

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [8]:
a2 = np.arange(0,10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a3 = np.array([3.4, 6.7, 7.8])
np.searchsorted(a2, a3)

array([4, 7, 8], dtype=int64)

In [12]:
np.searchsorted(a2, a3,side = 'right')

array([4, 7, 8], dtype=int64)

In [14]:
np.searchsorted(a2, a3,side = 'left')

In [16]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Data management functions in Numpy

In [29]:
a1 = np.arange(10)

In [21]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a1.shape

(10,)

In [23]:
a1.shape = 2,5

In [24]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
a1.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
a1.shape = 3,4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [31]:
a2 = np.arange(5)

In [32]:
a2

array([0, 1, 2, 3, 4])

In [ ]:
#np.newaxis dùng để tăng chiều của 1 ma trận lên 1
# nó là 1 tham số đại diện

In [36]:
a3 = a2[np.newaxis,:]
a3

array([[0, 1, 2, 3, 4]])

In [37]:
a3.shape

(1, 5)

In [38]:
a2.shape

(5,)

In [39]:
a3 = a2[:,np.newaxis]
a3

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [40]:
a3.shape

(5, 1)

In [41]:
a2

array([0, 1, 2, 3, 4])

In [43]:
a2 = np.arange(5)
a2

array([0, 1, 2, 3, 4])

In [44]:
a3 = a2[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [45]:
a4 = a2[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [46]:
a3.shape

(5, 1)

In [47]:
a4.shape

(3,)

In [49]:
a5 = a2[:,np.newaxis, np.newaxis]
a5.shape

(5, 1, 1)

In [50]:
a5

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [ ]:
# SQUEEZE : Giảm chiều dữ liệu

In [51]:
a5 = a5.squeeze()
a5.shape

(5,)

In [52]:
a4

array([4, 7, 8], dtype=int64)

In [2]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2.shape = 2,5
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# ma trận chuyển vị

In [18]:
import numpy as np

In [4]:
a2.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [5]:
a2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

# Phép nối

In [6]:
a6 = np.array([[1, 2, 3],[4, 5, 6]])
a6

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a7 = np.array([[41, 51, 61],[71, 81, 91]])
a7

array([[41, 51, 61],
       [71, 81, 91]])

In [8]:
a8 = np.concatenate((a6,a7))
a8

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [41, 51, 61],
       [71, 81, 91]])

In [9]:
a8 = np.concatenate((a6,a7), axis = 1)
a8

array([[ 1,  2,  3, 41, 51, 61],
       [ 4,  5,  6, 71, 81, 91]])

In [10]:
np.vstack((a6, a7))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [41, 51, 61],
       [71, 81, 91]])

In [11]:
np.hstack((a6, a7))

array([[ 1,  2,  3, 41, 51, 61],
       [ 4,  5,  6, 71, 81, 91]])

# Làm phẳng ma trận

In [13]:
a8.flatten()

array([ 1,  2,  3, 41, 51, 61,  4,  5,  6, 71, 81, 91])

In [14]:
a8

array([[ 1,  2,  3, 41, 51, 61],
       [ 4,  5,  6, 71, 81, 91]])

In [15]:
a8.ravel()

array([ 1,  2,  3, 41, 51, 61,  4,  5,  6, 71, 81, 91])

# Functions to create arrays in Numpy

In [16]:
np.arange(5, 40,5)

array([ 5, 10, 15, 20, 25, 30, 35])

In [46]:
a7 = np.arange(5, 40,5, dtype = np.float32)

In [26]:
np.linspace(0, 10, 30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [31]:
a1 = np.linspace(-10, 10, 5)
a1

array([-10.,  -5.,   0.,   5.,  10.])

In [32]:
a2 = np.linspace(-10, 10, 5)

In [33]:
x, y = np.meshgrid(a1, a2)

In [34]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [35]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

# Functions to create vectors in Numpy

In [36]:
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
np.zeros(3)

array([0., 0., 0.])

In [40]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.ones((2,3)) * 75

array([[75., 75., 75.],
       [75., 75., 75.]])

In [45]:
np.ones((2,3),dtype = np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
a3 = np.array([1, 2, 3, 4, 5, 6])
a3

array([1, 2, 3, 4, 5, 6])

In [49]:
np.zeros_like(a3)

array([0, 0, 0, 0, 0, 0])

In [50]:
np.ones_like(a3)

array([1, 1, 1, 1, 1, 1])

In [51]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Logical operators in Numpy

In [52]:
import numpy as ap

In [53]:
a1 = np.array([1,1, 1, 1])
a2 = np.array([1,1, 1, 8])
a1 == a2

array([ True,  True,  True, False])

In [54]:
a1 = np.array([1,1, 1, 1, 2])
a2 = np.array([1,1, 1, 8])
a1 == a2

<ipython-input-54-2d6ea017f19b>:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a1 == a2


False

In [55]:
a1 = np.array([1,1, 1, 1, 2])
a2 = np.array([1,1, 1, 8, 2])
a1 == a2

array([ True,  True,  True, False,  True])

In [56]:
a1 != a2

array([False, False, False,  True, False])

In [57]:
a1 <= a2

array([ True,  True,  True,  True,  True])

# Random in NUMPY

In [1]:
import numpy as np

In [2]:
# khởi tạo bộ (matraan 3x4) số ngẫu nhiên nằm từ 0 --> 1
np.random.rand(3,4)

array([[0.09235242, 0.11710477, 0.08055853, 0.40026696],
       [0.58704163, 0.92395162, 0.55468509, 0.05184865],
       [0.53445978, 0.16666598, 0.98669423, 0.42467336]])

In [3]:
# Khởi tạo bộ số ngẫu nhiên từ 0 đến 1
np.random.rand(10)

array([0.47882621, 0.1598101 , 0.37656403, 0.90744278, 0.09495924,
       0.90792157, 0.28727872, 0.03060312, 0.60356125, 0.6103909 ])

In [22]:
# cài đặt độ chính xác của bộ số ngẫu nhiên
np.set_printoptions(precision = 3)
np.random.rand(10)

array([0.539, 0.419, 0.685, 0.204, 0.878, 0.027, 0.67 , 0.417, 0.559,
       0.14 ])

In [6]:
# tạo 1 bộ số ngẫu nhiên có giá trị bk (<30) và có kích thước mảng bk (5x6)
np.random.randint(30, size = (5,6))

array([[21, 16,  8, 24, 19, 25],
       [10, 19, 26, 13,  1, 16],
       [ 3, 26, 29,  6, 18, 23],
       [ 1,  8, 23, 11, 20,  9],
       [ 4, 20, 17, 27,  4, 13]])

In [7]:
np.random.randint(0, 30, 7)

array([23, 29, 28, 14, 13,  2, 18])

In [8]:
a1 = np.arange(100)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
# Hàm xáo trộn
np.random.shuffle(a1)
a1

array([40, 36, 32, 43, 29, 44, 20, 19, 31, 21, 68, 94,  2, 81, 82, 42, 69,
       88,  4, 41, 52, 97, 45, 24, 90, 47, 64, 99, 18, 96, 91, 56, 39, 60,
        1,  6, 86, 80, 55, 76, 67, 71, 26, 38, 34, 95, 14, 79, 62, 98, 11,
       23, 17, 28, 46, 84, 37,  5, 77, 54, 13, 61, 87, 89, 53, 15, 30, 51,
       59, 12, 22, 58, 65, 78, 57, 66, 70, 48, 85,  7, 27, 74, 72, 73, 16,
       25, 10,  0, 93, 63, 75,  9, 49,  8, 92,  3, 50, 35, 33, 83])

In [20]:
# chọn 1 bộ số ngẫu nhiên và bộ số này sẽ không thay đổi
# nếu chạy lại hàm random (hàm chỉ định hạt giống)
np.random.seed(1)

In [21]:
np.random.rand(3,3)

array([[4.170e-01, 7.203e-01, 1.144e-04],
       [3.023e-01, 1.468e-01, 9.234e-02],
       [1.863e-01, 3.456e-01, 3.968e-01]])

# Reading file in Numpy

In [23]:
import numpy as np

In [24]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a1

array([1, 2, 3, 4, 5, 6])

In [26]:
np.savetxt("np_test4.txt", a1)

In [27]:
np.savetxt("np_test4.txt", a1, fmt = "%d")

In [28]:
np.savetxt("np_test4.txt", a1, fmt = "%.2f")

In [29]:
a2 = np.array([1, 2, 3, 4, 5, 6])
a1

array([1, 2, 3, 4, 5, 6])

In [36]:
np.save("np_test5.npy",a2)

In [37]:
a3 = np.load("np_test5.npy")
a3

array([1, 2, 3, 4, 5, 6])

In [38]:
a4 = np.arange(100)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
np.savez("np_test6.npz",a = a3, b = a4)

In [41]:
dict1 = np.load("np_test6.npz")

In [47]:
for i in dict1.keys():
    print(i, dict1[i])

a [1 2 3 4 5 6]
b [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# Practice with Numpy

# Exercise 1
Task: Invert the position of two lines in any matrix

In [1]:
import numpy as np

In [10]:
def invertLines(matrix,n1, n2):
    # matrix là mảng, n1 và n2 là index của các dòng muốn đảo bị trí
    for i in range(len(matrix[n1])):
        temp = matrix[n1][i]
        matrix[n1][i] = matrix[n2][i]
        matrix[n2][i] = temp

In [22]:
def invertLines_eff(matrix,n1, n2):
    # matrix là mảng, n1 và n2 là index của các dòng muốn đảo bị trí
    matrix[[n1,n2]] = matrix[[n2,n1]]

In [6]:
a1 = np.random.randint(30, size = (5,6))
a1

array([[19,  4, 23, 28, 22, 18],
       [25, 28, 26,  3,  7,  3],
       [ 6, 21,  1, 15, 22, 14],
       [17, 10, 12,  4, 17, 14],
       [ 0, 16, 19, 25,  3, 23]])

In [11]:
invertLines(a1,1, 2)
a1

array([[19,  4, 23, 28, 22, 18],
       [ 6, 21,  1, 15, 22, 14],
       [25, 28, 26,  3,  7,  3],
       [17, 10, 12,  4, 17, 14],
       [ 0, 16, 19, 25,  3, 23]])

In [23]:
a2 = np.arange(18).reshape(3,6)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [25]:
invertLines_eff(a2, 1, 2)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11]])

# Exercise 2:
Task: quickly search any number of higher values in an array
Tìm n số có giá trị cao nhất trong mảng

In [51]:
import numpy as np

In [ ]:
def searchHigherValue(arr, val):
    np.greater()
    

In [29]:
a1 = np.arange(800)
np.random.shuffle(a1)
a1

array([245,  42, 371, 586, 200, 414, 603, 136, 339, 683, 149, 388,  21,
       216, 255, 139, 652, 305, 382, 333, 503, 409, 494, 299, 621, 576,
        32, 130, 501, 420, 717,  72, 798, 300,  61, 278, 750, 169,  27,
       478, 350, 663, 532, 170, 507, 224, 404, 446, 330, 618, 530, 648,
       666, 744, 176, 779, 484, 616, 722, 177, 298, 569, 173, 538, 267,
       439, 506, 223, 748, 582, 544, 197, 189,  68, 655, 118, 411, 230,
       180,  65, 635, 146, 247, 534,  56, 141,  71,   7, 747, 386, 789,
       272,  84, 105, 740,  26,  88, 449, 368, 303,  34, 167, 366, 694,
       627, 427, 659, 676, 204,  10, 235, 526, 275,  90, 604, 474, 644,
       617, 253, 174, 198, 713, 289, 745, 488, 645, 462, 721,  18, 691,
       154, 271, 435, 574,  79, 730, 518, 227, 680, 524,  94,  70, 116,
       309, 762,  99, 231, 646, 423, 293, 469,   4, 438, 387, 575, 241,
       310, 665, 791, 697, 549, 210, 421,  89, 545, 258, 690, 553, 274,
       430, 157, 314, 797, 759, 610, 766, 658, 327, 463, 725, 56

In [54]:
#a2 = np.random.randint(10,size = (5,2))
a2 = np.random.randint(10, size=(1,9))
a2

array([[2, 8, 8, 1, 0, 8, 5, 3, 6]])

In [55]:
a3 = np.arange(10)
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a2 = np.random.randint(0,10, 9)
a2

array([9, 3, 2, 4, 1, 8, 6, 0, 4])

In [79]:
a2[5]

8

In [82]:
n = 0
ind1 = np.argpartition(-a2,n, axis = 0)
ind1

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [84]:
a2[ind1[:n+1]]

array([9])

# EXERCISE 3
Task: create an array consisting of zeros and display the used memory

In [85]:
a1 = np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [87]:
print("%d bytes" %(a1.size * a1.itemsize))

40 bytes


# Exercise 4
Task: to create a 4x4  size array of all 1 and outer frame made of zeros

In [1]:
import numpy as np

In [4]:
a1 = np.ones((4,4),dtype = int)
a1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
a1 = np.pad(a1,pad_width = 1, mode = 'constant', constant_values = 0)
a1

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

# Exericise 5
Task: print every day of November 2018

In [8]:
import numpy as np

In [10]:
a1 = np.arange("2018-11","2018-12",dtype = "datetime64[D]")
a1

array(['2018-11-01', '2018-11-02', '2018-11-03', '2018-11-04',
       '2018-11-05', '2018-11-06', '2018-11-07', '2018-11-08',
       '2018-11-09', '2018-11-10', '2018-11-11', '2018-11-12',
       '2018-11-13', '2018-11-14', '2018-11-15', '2018-11-16',
       '2018-11-17', '2018-11-18', '2018-11-19', '2018-11-20',
       '2018-11-21', '2018-11-22', '2018-11-23', '2018-11-24',
       '2018-11-25', '2018-11-26', '2018-11-27', '2018-11-28',
       '2018-11-29', '2018-11-30'], dtype='datetime64[D]')

# Exercise 6
Task: get the integer of a number of decimal

In [11]:
#import numpy as np

In [13]:
a1 =  np.random.rand(5)* 100
a1

array([37.4023234 ,  4.48765415, 61.74977733, 90.29093211,  9.49076123])

In [14]:
np.floor(a1)

array([37.,  4., 61., 90.,  9.])

In [15]:
np.ceil(a1)

array([38.,  5., 62., 91., 10.])

# Exercise 7
Task: create an array that can only be read but not written of modified

In [17]:
a1 = np.random.randint(0,10,9)
a1

array([5, 3, 3, 9, 4, 4, 7, 6, 6])

In [18]:
a1.flags.writeable = False

In [19]:
a1[0]=11
a1

ValueError: assignment destination is read-only